#-------------------------------
# General Site Settings
title: Wint Thandar Oo
description: "Hi, I'm Wint! I'm a professional working in software technology. This is my professional portfolio showcasing a variety of projects/tutorials that I have done by following the courses or books. You can visit my Github & LinkedIn profiles or download my resume using the links."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

#-------------------------------
# About Section
subtitle: Professional <span style="color:#f58506"> Portfolio </span>
location: "Yangon, Myanmar"
resume_url: /docs/Wint%20Thandar%20Oo%20Resume%202023.docx
avatar_image: img/profile_picture.jpg
#-------------------------------
# Contact links
linkedln: "https://www.linkedin.com/in/wintthandaroo/" # Add your linkedln handle
github: "https://github.com/Wint-Thandar"  # Add your github handle

#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-toc

paginate: 6
paginate_path: "/page/:num"
locale: en

sass:
  sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

defaults:
  - scope:
      type: posts
      values:
      layout: post
      read_time: true
      share: true

#-------------------------------
# TOC settings
toc:
 min_level: 1
 max_level: 3
 list_class: toc
 list_class: toc__list
 sublist_class: toc__sublist
 
#-------------------------------
# Google Analytics settings
 google_analytics: G-5Q5EYVF2FJ
 
#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
